openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /example:
    get:
      summary: Get example
      operationId: getExample
      responses:
        '200':
          description: Successful operation
